services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "5432:5432"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/static
      - ./media:/app/media
    networks:
      - app-network
    depends_on:
      - web

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge